version: '3.9'
services:
  api:
    build: .
    env_file: .env
    ports: ["8060:8060"]
    depends_on: [db, redis]
  db:
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports: ["3306:3306"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
volumes:
  dbdata:
